# Generated by Django 3.0.5 on 2020-04-03 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_pagelink_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='first_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_name', to='book.BookPage'),
        ),
    ]
