# Generated by Django 3.0.5 on 2020-04-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20200430_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpage',
            name='items',
            field=models.ManyToManyField(to='book.Item'),
        ),
    ]
