# Generated by Django 3.0.5 on 2020-05-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_pagelink_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_art',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='items',
            field=models.ManyToManyField(blank=True, to='book.Item'),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookprogress',
            name='items',
            field=models.ManyToManyField(blank=True, to='book.Item'),
        ),
        migrations.AlterField(
            model_name='pagelink',
            name='items',
            field=models.ManyToManyField(blank=True, to='book.Item'),
        ),
    ]
