# Generated by Django 3.0.5 on 2021-02-10 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20200526_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.BookPage')),
                ('items', models.ManyToManyField(blank=True, to='book.Item')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.BookProgress')),
            ],
        ),
    ]
