# Generated by Django 3.0.5 on 2021-02-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_progresssave'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresssave',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
