# Generated by Django 3.0.5 on 2021-06-04 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='progress',
            field=models.ForeignKey(default=42, on_delete=django.db.models.deletion.CASCADE, to='book.BookProgress'),
            preserve_default=False,
        ),
    ]
